SELECT Company_Data.Name, 
Company_Financials.ROCE,
Company_Financials.ROE, 
Company_Financials.Debt_Equity FROM Company_Data
INNER JOIN Company_Financials ON Company_Data.Name = Company_Financials.Name
WHERE Company_Financials.ROCE>30 and Company_Financials.Debt_Equity<1

SELECT Company_Data.Name, 
Company_Financials.ROCE,
Company_Financials.ROE, 
Valuations_Ratios.PE,
Valuations_Ratios.EV_EBITDA FROM Company_Data
INNER JOIN Company_Financials ON Company_Data.Name = Company_Financials.Name
INNER JOIN Valuations_Ratios ON Company_Data.Name = Valuations_Ratios.Name
WHERE Valuations_Ratios.PE<35

SELECT * from Valuations_Ratios

EXEC SP_RENAME 'Company_Financials','COS_FIN'
EXEC SP_RENAME 'Company_Data','COS_DATA'
EXEC SP_RENAME 'Valuations_Ratios','VALUE_RATIO'

EXEC sp_rename 'COS_DATA.Sales_growth', 'Sales_growth_3Y', 'COLUMN';
EXEC SP_RENAME 'COS_DATA.Profit_growth', 'Profit_growth_3Y', 'COLUMN';

SELECT COS_DATA.Name,
COS_DATA.Sales_growth_3Y, 
COS_DATA.Profit_growth_3Y,
COS_DATA.Net_profit_margin,
VALUE_RATIO.PB FROM COS_DATA
INNER JOIN VALUE_RATIO ON COS_DATA.Name = VALUE_RATIO.Name
WHERE COS_DATA.NAME LIKE '%Bank%' AND VALUE_RATIO.PB < 3

--PROCEDURE

CREATE OR ALTER PROCEDURE AS_PER_PE
@PE INT
AS
BEGIN
	SELECT COS_DATA.Name, 
	COS_DATA.Sales_growth_3Y, 
	COS_DATA.Profit_growth_3Y, 
	VALUE_RATIO.PE, 
	VALUE_RATIO.EV_EBITDA FROM COS_DATA
	INNER JOIN VALUE_RATIO ON COS_DATA.Name = VALUE_RATIO.Name
	WHERE VALUE_RATIO.PE < @PE
END
EXEC AS_PER_PE @PE = 30

CREATE OR ALTER PROCEDURE BK_VAL_PB
@PB INT, @S_GROWTH DECIMAL(10,2), @P_GROWTH DECIMAL(10,2) 
AS
BEGIN
	SELECT COS_DATA.Name, 
	COS_DATA.Sales_growth_3Y, 
	COS_DATA.Profit_growth_3Y, 
	VALUE_RATIO.PB 
	FROM COS_DATA
	INNER JOIN VALUE_RATIO ON COS_DATA.Name = VALUE_RATIO.Name
	WHERE COS_DATA.Name LIKE '%Bank%' AND VALUE_RATIO.PB < @PB AND COS_DATA.Sales_growth_3Y > @S_GROWTH AND COS_DATA.Profit_growth_3Y > @P_GROWTH
END
EXEC BK_VAL_PB @PB = 3, @S_GROWTH = 15, @P_GROWTH = 10

CREATE OR ALTER PROCEDURE STCK_VAL_GRTH
@EVEBITDA DECIMAL(10,2),
@ROCE DECIMAL(10,2)
AS
BEGIN
	SELECT COS_FIN.Name,
	COS_FIN.ROCE,
	VALUE_RATIO.EV_EBITDA,
	COS_DATA.Sales_growth_3Y,
	COS_DATA.Profit_growth_3Y FROM COS_FIN
	INNER JOIN COS_DATA ON COS_FIN.Name = COS_DATA.Name
	INNER JOIN VALUE_RATIO ON COS_FIN.Name =VALUE_RATIO.Name
	WHERE VALUE_RATIO.EV_EBITDA >= @EVEBITDA AND COS_FIN.ROCE >= @ROCE
END
EXEC STCK_VAL_GRTH 25, 30

--FUNCTION

CREATE FUNCTION Cos_Growth(@NAME VARCHAR(100))
RETURNS TABLE
AS
	RETURN (SELECT NAME, Sales_growth_3Y, Profit_growth_3Y FROM COS_DATA
	WHERE @NAME = Name)

CREATE FUNCTION CC(@NAME VARCHAR(100))
RETURNS TABLE
AS
	RETURN (SELECT NAME, Debtor_days, Cash_cycle FROM COS_DATA
	WHERE @NAME = Name)

CREATE OR ALTER FUNCTION CC_ZERO()
RETURNS VARCHAR(100)
AS
BEGIN 
	RETURN (SELECT TOP 1 NAME FROM COS_DATA WHERE Cash_cycle = 0)
END

CREATE OR ALTER FUNCTION DEBT_TO_EQUITY_ZERO()
RETURNS VARCHAR(100)
AS
BEGIN 
	RETURN (SELECT TOP 1 NAME FROM COS_FIN WHERE Debt_Equity = 0)
END

--TRIGGER

CREATE OR ALTER TRIGGER INFO_INSERT_COS_FIN
ON COS_FIN
FOR INSERT 
AS
BEGIN
	DECLARE @NAME VARCHAR(100)
	SELECT @NAME = Name FROM inserted
	PRINT CONCAT('COMPANY NAME ',@NAME,' RECORD INSERTED INTO COS_FIN')
END

INSERT INTO COS_FIN VALUES ('HAL', 38.9, 28.9, 0)

CREATE OR ALTER TRIGGER INFO_UPDATE_COS_FIN
ON COS_FIN
FOR UPDATE 
AS
BEGIN
	DECLARE @NAME VARCHAR(100)
	SELECT @NAME = Name FROM inserted
	PRINT CONCAT('COMPANY NAME ',@NAME,' RECORD UPDATED ON COS_FIN')
END

UPDATE COS_FIN SET NAME = 'Hindustan Aeronautics Ltd' WHERE NAME = 'HAL'

CREATE OR ALTER TRIGGER INFO_DELETE_COS_FIN
ON COS_FIN
FOR DELETE 
AS
BEGIN
	DECLARE @NAME VARCHAR(100)
	SELECT @NAME = Name FROM deleted
	PRINT CONCAT('COMPANY NAME ',@NAME,' DELETED FROM COS_FIN')
END

DELETE FROM COS_FIN WHERE NAME = 'Hindustan Aeronautics Ltd'

--CURSOR

DECLARE @NAME VARCHAR(100), @ROCE DECIMAL(8,2), @ROE DECIMAL(8,2);

DECLARE INFO_COS_FIN CURSOR FOR 
SELECT Name, ROCE, ROE FROM COS_FIN;

OPEN INFO_COS_FIN;

FETCH NEXT FROM INFO_COS_FIN INTO @NAME, @ROCE, @ROE;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT CONCAT(UPPER(@NAME), ' HAVE ', @ROCE, ' ROCE AND ', @ROE, ' ROE');
    FETCH NEXT FROM INFO_COS_FIN INTO @NAME, @ROCE, @ROE;
END;

CLOSE INFO_COS_FIN;
DEALLOCATE INFO_COS_FIN;


DECLARE @NAME VARCHAR(100), @SALES_GRWTH DECIMAL(5,2), @PROFIT_GRWTH DECIMAL(8,2);

DECLARE INFO_GRWTH_COS_DATA CURSOR FOR 
SELECT Name, Sales_growth_3Y, Profit_growth_3Y FROM COS_DATA;

OPEN INFO_GRWTH_COS_DATA;

FETCH NEXT FROM INFO_GRWTH_COS_DATA INTO @NAME, @SALES_GRWTH, @PROFIT_GRWTH;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT CONCAT(UPPER(@NAME),' REPORTED 3 YEAR ','SALES GROWTH OF ',@SALES_GRWTH,' AND ','PROFIT GROWTH OF ',@PROFIT_GRWTH);
    FETCH NEXT FROM INFO_GRWTH_COS_DATA INTO @NAME, @SALES_GRWTH, @PROFIT_GRWTH;
END;

CLOSE INFO_GRWTH_COS_DATA;
DEALLOCATE INFO_GRWTH_COS_DATA;